# Despliegue de app Flask en Azure Web App desde GitHub Actions

name: Build and deploy Python app to Azure Web App - crud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Empaquetar aplicación para despliegue
        run: |
          zip -r app.zip . -x "venv/*" "__pycache__/*" ".git/*" ".github/*"

      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'crud'  # Nombre exacto del App Service en Azure
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_45AA9267D2A74512B463CF23615A610A }}
          package: app.zip
